# Generated by Django 5.1.1 on 2024-09-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
