# Generated by Django 5.1.1 on 2024-09-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_alter_booking_creation_time_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17)),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=40)),
            ],
        ),
    ]
